words = [
    'IIV',
    'TATU',
    'XTB',
    'OAK',
    'DTM',
    'XTB',
    "OʻzAS",
    'BMT',
    'YUNESKO',
    'XXR',
    'RF',
    'AQSH',
    'OʻzXDP',
    'NATO',
    'FIFA',
    'AES',
    'GES',
    'EHM',
    'SI',
    'LMS',
    'NBU',
    'JDPU',
    'JDU',
    'IDU',
    "OʻzMU",
    'ON',
    'UFC',
    'MMA',
    'SHK',  
]

shorts = {
    "lms": "LMS",
    'aes': 'AES',
    'ges': 'GES',
    'ehm': 'EHM',
    'e.h.m': 'EHM',
    'si': 'SI',
    's.i': 'SI',
    'nato': 'NATO',
    'fifa': 'FIFA',
    'rf': 'RF',
    'u.s.a': 'AQSH',
    'usa': 'AQSH',
    'oʻzdp': "OʻzDP",
    'ufc': 'UFC',
    'mma': 'MMA',
    'shk': 'SHK',
    'oak': 'OAK',
    'dtm': 'DTM',
    'xtb': 'XTB',
    'iiv': 'IIV',
    'tatu': 'TATU',
    'bmt': 'BMT',
    'unesco': 'YUNESKO',
    'yunesko': 'YUNESKO',
    'xxr': 'XXR',
    'nbu': 'NBU',
    'jdpu': 'JDPU',
    'jdu': 'JDU',
    'idu': 'IDU',
    'oʻzmu': "OʻzMU",
    'on': 'ON',
    'oʻzas': "OʻzAS",
    "o'zas": "OʻzAS",
    "o'z as": "OʻzAS",
    "o'zmu": "OʻzMU",
    "o'zlidep": "OʻzLIDEP",
    "o`zlidep": "OʻzLIDEP",
    "o`zmu": "OʻzMU",
    
    
    
    
}

